# Generated by Django 5.0.6 on 2024-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                choices=[
                    ("Developer", "Developer"),
                    ("Project Manager", "Project Manager"),
                    ("Designer", "Designer"),
                    ("DevOps", "DevOps"),
                    ("QA", "QA"),
                ],
                max_length=255,
            ),
        ),
    ]
