# Generated by Django 5.0.6 on 2024-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_position_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.CharField(
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("In Review", "In Review"),
                    ("Testing", "Testing"),
                    ("Done", "Done"),
                ],
                default="To Do",
                max_length=15,
            ),
        ),
    ]
