# Generated by Django 5.0.6 on 2024-05-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0004_remove_task_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["deadline"]},
        ),
    ]
