# Generated by Django 5.0.6 on 2024-05-19 16:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="main_programming_language",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Mobile phone number",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
    ]
