# Generated by Django 5.0.6 on 2024-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_main_programming_language_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="main_programming_language",
            field=models.CharField(default="Not specified.", max_length=255),
        ),
    ]
